### ISSUE TITLE
Missing Functions..

### ISSUE THREAD

**Issue by Jonehx** [AdrianSchiel/Minecraft_GunGame#1]
-Arena delete command
-File Support
-Option to disable Scoreboard
-Arena editing after finishing Arena
-Team Help only in German (even after changing to english)
-Armor can get dragged out of the Armor Slot
![Screenshot 2021-07-31 133043](https://user-images.githubusercontent.com/88157137/127738539-5b43ed05-a093-433f-9eb0-78294e8ae37d.png)

**Comment by AdrianSchiel** [comment]
Arena delete command - DONE

**Comment by AdrianSchiel** [comment]
Option to disable Scoreboard - DONE

**Comment by AdrianSchiel** [comment]
Team Help only in German (even after changing to english) - DONE

**Comment by AdrianSchiel** [comment]
Armor can get dragged out of the Armor Slot - DONE

**Comment by AdrianSchiel** [comment]
Arena editing after finishing Arena - DONE

**Comment by AdrianSchiel** [comment]
File Support - Addet SQLite Support
